Update serialization.rb
facing issue when trying to install audited gem after globalize gem because gem trying to access undefined methods

``` (called from block (2 levels) in require at C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:60)
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/activerecord-7.1.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined local variable or method `globalize_serialized_attributes' for Audited::Audit:Class ```